---
deployment:
  tasks:
    - echo "Starting deployment..."
    - export COMPOSER_HOME=/home/kejadigital/.composer
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - echo "Deployment finished."
