---
deployment:
  tasks:
    - export COMPOSER_HOME=$HOME/.composer
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
